### ISSUE TITLE
Custom Spawn

### ISSUE THREAD

**Issue by Liv3ry** [LexManos/YUNoMakeGoodMap#10]
Hi, I wanted to ask if there is a way to modify or eliminate the spawn of YUNomakegoodmap, I should put my building as spawn.
If you can eliminate the spawn can I use another mod to create it, if I can put it directly in Yuno then it would be better.

I apologize for my English, not American-English

Thanks for your attention, Liv3ry.

**Comment by LexManos** [comment]
Theoretically I wanted to add the ability to import schematics as the spawn, but never got around to doing that..

**Comment by Liv3ry** [comment]
You could eliminate the structure so that spawn with another mod I put it?

**Comment by LexManos** [comment]
Default setup is one dirt block, so go that route.

**Comment by LexManos** [comment]
This has been added in the 1.10.2 version.
