### ISSUE TITLE
Sky Factory 2 Modpack RFTools Void Dimensions

### ISSUE THREAD

**Issue by Sauroth** [LexManos/YUNoMakeGoodMap#12]
Greetings. I have a 1.7.10 server running SF2 Modpack, and i have RFTools Mod installed, but the Dimension Builder generates empty void dimensions. If I disable YUNoMakeGoodMap it creates 'normal' dimensions. Can you implement a RFTools compatibility, an exception for these dimensions or a way to choose which dimensions to be void?

**Comment by LexManos** [comment]
Just disable the global option to override the standard world type and use the VOID world type for worlds you want void.

**Comment by Sauroth** [comment]
Still doesn't work. It overrieds every terrain void somehow.

**Comment by LexManos** [comment]
https://github.com/LexManos/YUNoMakeGoodMap/blob/master/src/main/java/net/minecraftforge/lex/yunomakegoodmap/YUNoMakeGoodMap.java#L66 Set that to false and it won't.

**Comment by Sauroth** [comment]
I did that.

**Comment by Sauroth** [comment]
I've tried every combination possible. It seems the only way to stop generating empty dimensions is to disable the YUNoMakeGoodMaps mod. It generates structures, but it doesn't want to create the terrain.
![11](https://cloud.githubusercontent.com/assets/13009524/8298398/f6c947e6-1970-11e5-8b28-bb0a2c65dc95.png)

**Comment by Sauroth** [comment]
I think i know what the problem is. 

return overrideDefault || world.getWorldInfo().getTerrainType() == worldType;

Each dimension's terrain generated is TERRAIN_VOID, so I guess it tells it to make it void no matter what.

**Comment by LexManos** [comment]
Yes, if you set the world type to void all dimensions will be void.. You shouldn't do that.
Maybe the RF dimensions are using the overworld/void world type. No clue.

**Comment by Sauroth** [comment]
No. Even if I set it to default world generator, the overworld starting dimension has all the terrain, mobs and trees. It's just the RF dimensions who are perceived as void, because of this line:

 return overrideDefault || **world.getWorldInfo().getTerrainType() == worldType;**

There's no other type of terrain type for RF dimensions. They are all void type and the mod creates the terrain chunks according to the settings..but instead of loading the normal materials, YUNOMGM perceives they should be void.

**Comment by Sauroth** [comment]
FIXED: RFTools has a config where the other type of terrain dimlets are blacklisted. Now it works as it should. Thanks.
