### ISSUE TITLE
Allow generation in Nether and End when config has overrideDefault=true

### ISSUE THREAD

**Issue by LegendLength** [LexManos/YUNoMakeGoodMap#15]
Currently it is not possible to force all new worlds to be void without also clearing out The Nether and The End dimensions.

I have made a small change that adds the config options:

populateNether=true
populateEnd=true

This allows a setup where the user always get a void overworld (no need for them to set world type to void before starting) and also allows the Nether and End to generate normally.

Is it normal procedure to create a pull request for review?  This is my first time using git although I've used other source control before so I'm not sure of the right way to submit this.  I will try to do the procedure from online documentation anyway and please let me know if I do something wrong or out of line, or if the feature is not desirable at all.

**Comment by OvermindDL1** [comment]
Yes, you should always submit a PR for such changes.

**Comment by LexManos** [comment]
The new system you should not use overrideDefault. Just use void world type. This shouldnt be an issue.
