### ISSUE TITLE
Weird black box around player foot below level 66 eye level

### ISSUE THREAD

**Issue by Nagapito** [LexManos/YUNoMakeGoodMap#17]
I noticed this strange behaviour with your mod. 

The worlds created with your mod, render a black box around player feed when camera is below level 63

You can see on the screens I uploaded that all is normal above level 63 but as soon the camera goes below level 63, there is this strange box rendered that extends to infinity.
It doest seem to affect blocks. Blocks seem to always be draw over it but it affects the skybox and when we use mods like Stellar Sky, we have a huge black box below us screwing the beautiful skybox...  
  
It also seems to affect the world permanently, since even after I remove the mod, the box is still there!

Besides a mod fix to prevent this happening, is there a way to also fix the worlds already generated? Some NBT fix or MCEdit..? 

Thanks.

PS: Love your little mod, best mod to make skyblocks packs!

![2016-04-04_22 14 03](https://cloud.githubusercontent.com/assets/4959346/14263485/cdb71bca-fab2-11e5-9d8c-55468245b45b.png)
![2016-04-04_22 14 33](https://cloud.githubusercontent.com/assets/4959346/14263486/cdba0862-fab2-11e5-8ad2-a430ed5bfc4d.png)
![2016-04-04_22 14 40](https://cloud.githubusercontent.com/assets/4959346/14263487/cdbd1b9c-fab2-11e5-869e-1f9ee497b4ce.png)
![2016-04-04_22 14 46](https://cloud.githubusercontent.com/assets/4959346/14263488/cdbe12d6-fab2-11e5-90ce-05710edf9411.png)
![2016-04-04_22 14 52](https://cloud.githubusercontent.com/assets/4959346/14263489/cdc0e2f4-fab2-11e5-928b-965b806078d9.png)
![2016-04-04_22 21 30](https://cloud.githubusercontent.com/assets/4959346/14263618/6be6be5e-fab3-11e5-8ba2-9ba3d172967b.png)
![2016-04-04_22 21 38](https://cloud.githubusercontent.com/assets/4959346/14263619/6be9097a-fab3-11e5-94a2-74e70c0ae71c.png)

**Comment by LexManos** [comment]
Blame the MC engine this mod has nothing to do with rendering.
