### ISSUE TITLE
Sauroth Void Dimensions reopened

### ISSUE THREAD

**Issue by COLDF1R3** [LexManos/YUNoMakeGoodMap#22]
Issue #12 mentions that he had a fix but ive read his "fix" and gone through both configs scouring for the config option he mentions to no avail. Im playing sky factory 2.5 and would like to make a mining world, however im unable to because when i generate the world it comes out as a void world with just a small platform. He says theres a blacklist of certain dimlets in the config, however im searched both configs for blacklist, terrain, flat, etc anything to try to find the terrain flat dimlet but i can not for the life of me find this. unless im missing a config somewhere ive checked both the dimlets.cfg and main.cfg under the servers config/rftools directory. Thank you for any help.

**Comment by LexManos** [comment]
I do not control other people's dimensions.
Same answer as before, disable the global config and use the VOID type.
