### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by mttprvst13** [LexManos/YUNoMakeGoodMap#23]
Where can I download the latest version of this mod? I know there is the 1.8 and lower versions on the forge website, but I saw there was an update to 1.10. Is that on the forge website, or is there another place to download?

**Comment by LexManos** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/lex/YUNoMakeGoodMap
As with everything that is pushed to our maven it has a download page.
