### ISSUE TITLE
Dragon Fight Freezes Game

### ISSUE THREAD

**Issue by Darkosto** [LexManos/YUNoMakeGoodMap#24]
While fighting the dragon in a void end, the dragon lands on the portal for his phase 2 attacks (breath attack on ground). When this happens and the player is in survival, the game will completely freeze up and cause java to stop responding. 

On investigation, placing endstone around the portal will allow the game to function normally.

https://sx.artdude.uk/hotlink-ok/darkosto/Ivia-ea88d-1475108463.png

1. I think the best case scenario is to either allow the end to generate normally with land 2. Create a platform around the portal or 3. Handle the breath mechanic without a ground below

**Comment by GenDeathrow** [comment]
Vanilla's nice infinite loop >> http://i.imgur.com/cIPvcgK.png

In PhaseSittingFlaming.class for dragon.

**Comment by LexManos** [comment]
That'd do it they don't have any sane work around for that.... On a void world... Really Mojang?

**Comment by Darkosto** [comment]
LOL! Any possibility of just keeping the end normal gen? At least for now?

**Comment by LexManos** [comment]
no ill fix it when i get a chance

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/cfa63792bc4230a6e44230ec2504a9178f78e46e
