### ISSUE TITLE
1.10.2

### ISSUE THREAD

**Issue by Kashdeya** [LexManos/YUNoMakeGoodMap#29]
Is there any way to use a Schematic for the starting island?

**Comment by LexManos** [comment]
https://github.com/LexManos/YUNoMakeGoodMap/commit/88769ad6613e06d35525acc6699c3389767524a2
Thats when I added it, 1.10.2 6.1.0+ has it.

**Comment by Kashdeya** [comment]
Can you please explain on how to use a Schematic file? Because I can not find any info on it. 

I have noticed that the Config files says it supports .NBT files but I was asking about a Schematic file from worldedit or MCEdit. the NBT way does not allow you to make big starting islands.

**Comment by LexManos** [comment]
Ah, no i will not be adding support for schametic format, first off, it's a old outdated unflexible format. The last time I looked at it the structure format was far superior {not perfect but way better}
And you can make any size platform you want with the structure format. The vanilla blocks limit the size, but the file format doesn't. So talk to the worldedit people and im sure they can easily add support for saving in that formt.
