### ISSUE TITLE
[1.7.10] World not generating

### ISSUE THREAD

**Issue by rockbanddude** [LexManos/YUNoMakeGoodMap#31]
So I installed the mod and set up the tree profile in the configs, but when I generated the world it dropped me straight into the void. No tree. I then tried skyblock 2.1 profile and still nothing.

**Comment by LexManos** [comment]
1.7.10 works, it's been tested and functions just fine for thousands of people.
However, if it doesn't, it doesn't matter as 1.7.10 has been EOLed.
