### ISSUE TITLE
Ignoring YUNoMakeGoodMap

### ISSUE THREAD

**Issue by Bubble0seven** [LexManos/YUNoMakeGoodMap#33]
Fresh install of skyfactory 3 and the commands for createislandfor worked for a few then after a restart it no longer works. 

Going through the log file i see this line 

[23:56:52] [Server thread/DEBUG] [FML/]: Ignoring unknown file YUNoMakeGoodMap-1.10.2-6.1.0.26.jar. in mods directory

[FML Latest Log](https://gist.github.com/Bubble0seven/542feec5b0b40916451c44009a9e6950)

**Comment by AntonBoch1244** [comment]
Try rename "YUNoMakeGoodMap-1.10.2-6.1.0.26.jar." to "YUNoMakeGoodMap-1.10.2-6.1.0.26.jar"

**Comment by Bubble0seven** [comment]
thanks why did i not see that elusive full stop at the end  i will go get my eyes checked immediately lol  thanks bud

**Comment by Bubble0seven** [comment]
Yeah it seems to load by the looks of it but none of the commands work still keeps saying unkown commands 

[New Log](https://gist.github.com/Bubble0seven/b63f81bda15c062eda62d94c27162a49)

**Comment by AntonBoch1244** [comment]
@Bubble0seven same problem but other mod "ItsBecauseUHasNoGoodSpawn-1.0.5.jar." to "ItsBecauseUHasNoGoodSpawn-1.0.5.jar"

**Comment by Bubble0seven** [comment]
thanks i think one of the other owners been dabbling in it and not putting it back to how it was meant to be thanks
