### ISSUE TITLE
1.10 No Island Creation 

### ISSUE THREAD

**Issue by Bubble0seven** [LexManos/YUNoMakeGoodMap#34]
When I first spawn in i do spawn on the spawn island but when i run the /createislandfor  i just get dumped into the void with no island

[ItsBecauseNoGoodSpawn Config](https://gist.github.com/Bubble0seven/c3b6e55ea4b358e64e26cbfe8cd25773)

[YUNoMakeGoodMap Config](https://gist.github.com/Bubble0seven/7d7deeaafbb58cb2929aa68cfc997ce6)

[FML-Log](https://gist.github.com/Bubble0seven/2c2cc53395c017359d7e61400699dd2c)

Doesn't appear to be any errors in the logs so am I doing something incorrectly ??

**Comment by LexManos** [comment]
Only YUNMGM is mine, you can use it's /platform command to create a platform. I have no idea how the other mod works.
