### ISSUE TITLE
custom structure json? (1.10.2)

### ISSUE THREAD

**Issue by StrangeThistle** [LexManos/YUNoMakeGoodMap#35]
I am in the process of creating my own pack using YUNoMakeGoodMap-1.10.2-6.1.0.26, and I can't for the life of me figure out how or where to add the description for my custom platform in a way that will appear in the selection menu. Should it be a separate json file, or should it somehow be added into the YUNoMakeGoodMap.cfg file? Am I doing something completely wrong, or is the feature not actually working at the moment?

Here is a screenshot of what I am seeing.
![16177858_10210121602589910_8423153622067540088_o](https://cloud.githubusercontent.com/assets/8715948/22324110/3feb52aa-e375-11e6-8b73-92248a961640.jpg)

**Comment by LexManos** [comment]
Works just fine as you can see by all the current examples https://github.com/LexManos/YUNoMakeGoodMap/blob/master/src/main/resources/assets/yunomakegoodmap/structures/COBBLE_GEN.json

**Comment by Flabort** [comment]
This issue would more accurately be titled as "ONLY the examples work".
While the examples within the .jar file work, the submitter of this issue tried to copy the examples into the folder where mod-pack makers need to put these files, and [this](https://forum.feed-the-beast.com/threads/yunomakegoodmap.214630/#post-1826860) was the result.
