### ISSUE TITLE
Custom structure spawn area

### ISSUE THREAD

**Issue by LousyLynx** [LexManos/YUNoMakeGoodMap#41]
Hey, Lex. I am working on a new modpack, and have a suggestion for this mod. I would like to make a structure where you spawn at a specific location in the structure. I think a new NBT or JSON configuration option would be awesome, and generally not too difficult. Then again, most things in coding seem quite easy until you actually start trying to do it 😛. Thanks!

**Comment by LexManos** [comment]
https://github.com/LexManos/YUNoMakeGoodMap/commit/88769ad6613e06d35525acc6699c3389767524a2

**Comment by LousyLynx** [comment]
Ohh. My bad. Did not see that. Sorry!
