### ISSUE TITLE
Templates for other dimensions?

### ISSUE THREAD

**Issue by Mewr11** [LexManos/YUNoMakeGoodMap#45]
Is there a way to provide a default structure for the nether, end, and/or modded dimensions?

**Comment by LexManos** [comment]
https://github.com/LexManos/YUNoMakeGoodMap/blob/8a382187553c573a57c54951c1d81ee887e3202c/src/main/java/net/minecraftforge/lex/yunomakegoodmap/generators/StructureLoader.java#L30
{StructureName}_{dimension suffix} It's already implemented.
