### ISSUE TITLE
NetherEx Incompatibilites

### ISSUE THREAD

**Issue by UnlimatedStone9** [LexManos/YUNoMakeGoodMap#47]
NetherEx is a mod that overwrites the nether with its own unique generation, like how Biomes O' Plenty and Natura add to the dimension, However NetherEx overwrites the void aspect of this mod too which is frustrating when building a Modpack that is supposed to have vanilla dimensions as Pure Void,
I've already reported it on NetherEx's side too and I hope this is resolved

**Comment by LogicTechCorp** [comment]
This issue has been fixed in MineEx/NetherEX@19ecbb5b.
